<?php
/**
 * @var $block \Origines\CategoryWidget\Block\Widget\CategoryList
 */
?>
<div class="category-widget-main">
    <div class="category-list-slider">
        <?php $_category = $block->getCategory(); ?>
        <?php foreach ($_category as $category): ?>
            <?php $imgLogo = $category->getData('logo_image'); ?>
            <span class="category-list">
                <a href="<?=$block->escapeUrl($category->getUrl()); ?>">
                    <img alt="<?= $block->escapeHtml($category->getName()); ?>"
                     src="<?= $block->escapeUrl($block->getMediaUrl($imgLogo)); ?>"/>
                </a>
        </span>
        <?php endforeach; ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "slider": {}
        }
    }

</script>
